project:
  type: website

website:
  title: "Ethan Sansom"
  search: false
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts
      - href: packages.qmd
        text: Packages
  page-footer:
    left: "© 2025 Ethan Sansom"
    # Quarto uses bootstrap icons: https://icons.getbootstrap.com/?q=code
    right:
    - icon: github
      href: "https://github.com/EthanSansom"
      aria-label: GitHub
    - icon: code-slash
      href: "https://github.com/EthanSansom/ethansansom.com"
      aria-label: Website Repository

format:
  html:
    mainfont: Inter # Oswald (for testing)
    monofont: Fira Code
    theme:
      light: [flatly, assets/custom-theme-light.scss]
      dark: [darkly, assets/custom-theme-dark.scss]
    css: assets/custom-styles.css
    smooth-scroll: true
    link-external-newwindow: true
    highlight-style: gruvbox # TODO: Customize

editor: source
