project:
  type: website

website:
  title: "Ethan Sansom"
  search: false
  navbar:
    # title: "Ethan Sansom"
    right:
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts
      - href: packages.qmd
        text: Packages

format:
  html:
    mainfont: Inter
    theme:
      light: [flatly, assets/custom-theme-light.scss]
      dark: [darkly, assets/custom-theme-dark.scss]
    css: assets/custom-styles.css

editor: source
